# Generated by Django 3.0.5 on 2020-04-19 21:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
            ],
            options={
                'verbose_name': 'Asistentes a entrenamineto',
                'verbose_name_plural': 'Asistentes a entrenaminetos',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100)),
                ('points_infavor', models.IntegerField(blank=True, null=True)),
                ('points_against', models.IntegerField(blank=True, null=True)),
                ('winnig', models.BooleanField(null=True)),
                ('observation', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.DecimalField(decimal_places=3, max_digits=5)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('observation', models.TextField()),
            ],
            options={
                'verbose_name': 'Asistentes a entrenamineto',
                'verbose_name_plural': 'Asistentes a entrenaminetos',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=3, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=4)),
                ('years_played', models.IntegerField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('healthcare', models.CharField(max_length=300)),
                ('emergency_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Posicion',
                'verbose_name_plural': 'Posiciones',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('measure_unit', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('place', models.CharField(max_length=250)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('players', models.ManyToManyField(through='dashboard.Assistants', to='dashboard.Player')),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamientos',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='position_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='position_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_requests_created', to='dashboard.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='records',
            field=models.ManyToManyField(through='dashboard.Measure', to='dashboard.Record'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Played',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_duration', models.TimeField(blank=True, null=True)),
                ('end_duration', models.TimeField(blank=True, null=True)),
                ('observation', models.TextField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Player')),
            ],
            options={
                'verbose_name': 'Partido Jugado',
                'verbose_name_plural': 'Partidos Jugados',
            },
        ),
        migrations.AddField(
            model_name='measure',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Player'),
        ),
        migrations.AddField(
            model_name='measure',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Record'),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(through='dashboard.Played', to='dashboard.Player'),
        ),
        migrations.AddField(
            model_name='assistants',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Player'),
        ),
        migrations.AddField(
            model_name='assistants',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Training'),
        ),
    ]
