# Generated by Django 3.0.5 on 2020-04-21 19:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200420_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='emergency_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CL'),
        ),
    ]
