# Generated by Django 3.0.5 on 2020-04-22 16:01

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200421_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [-29.9045296, -71.2489395], 'marker_color': 'blue'}, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='measure_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
