# Generated by Django 3.0.5 on 2020-04-22 16:19

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200422_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [-29.915835830267262, -71.24076894770667], 'marker_color': 'blue'}, null=True),
        ),
    ]
