# Generated by Django 3.0.5 on 2020-04-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200422_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='training',
            name='long',
        ),
    ]
