# Generated by Django 3.0.5 on 2020-05-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200422_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measure',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
