# Generated by Django 3.0.5 on 2020-05-04 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200503_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure',
            options={'verbose_name': 'Medicion', 'verbose_name_plural': 'Mediciones'},
        ),
    ]
