# Generated by Django 3.0.5 on 2020-11-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200504_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
