# Generated by Django 3.0.5 on 2020-04-13 16:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Isue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100)),
                ('points_infavor', models.IntegerField(blank=True, null=True)),
                ('points_against', models.IntegerField(blank=True, null=True)),
                ('winnig', models.BooleanField(null=True)),
                ('observation', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.DecimalField(decimal_places=3, max_digits=5)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('observation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=3, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=4)),
                ('years_played', models.IntegerField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('healthcare', models.CharField(max_length=300)),
                ('emergency_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('measure_unit', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_favor', models.BooleanField(null=True)),
                ('isue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Isue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('place', models.CharField(max_length=250)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('players', models.ManyToManyField(through='core.Assistants', to='core.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('image', models.ImageField(upload_to='postImage/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='position_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='position_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_requests_created', to='core.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='records',
            field=models.ManyToManyField(through='core.Measure', to='core.Record'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Played',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_duration', models.TimeField(blank=True, null=True)),
                ('end_duration', models.TimeField(blank=True, null=True)),
                ('observation', models.TextField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Minute_Assistants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Minute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='minute',
            name='users',
            field=models.ManyToManyField(through='core.Minute_Assistants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measure',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player'),
        ),
        migrations.AddField(
            model_name='measure',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Record'),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(through='core.Played', to='core.Player'),
        ),
        migrations.AddField(
            model_name='isue',
            name='minute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Minute'),
        ),
        migrations.AddField(
            model_name='isue',
            name='votes',
            field=models.ManyToManyField(through='core.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assistants',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player'),
        ),
        migrations.AddField(
            model_name='assistants',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Training'),
        ),
    ]
