# Generated by Django 3.0.5 on 2020-04-13 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistants',
            options={'verbose_name': 'Asistentes a entrenamineto', 'verbose_name_plural': 'Asistentes a entrenaminetos'},
        ),
        migrations.AlterModelOptions(
            name='directive',
            options={'verbose_name': 'Directiva', 'verbose_name_plural': 'Miembros de la Directiva'},
        ),
        migrations.AlterModelOptions(
            name='isue',
            options={'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AlterModelOptions(
            name='measure',
            options={'verbose_name': 'Asistentes a entrenamineto', 'verbose_name_plural': 'Asistentes a entrenaminetos'},
        ),
        migrations.AlterModelOptions(
            name='minute',
            options={'verbose_name': 'Acta', 'verbose_name_plural': 'Actas'},
        ),
        migrations.AlterModelOptions(
            name='played',
            options={'verbose_name': 'Partido Jugado', 'verbose_name_plural': 'Partidos Jugados'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Posicion', 'verbose_name_plural': 'Posiciones'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Entrenamiento', 'verbose_name_plural': 'Entrenamientos'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Voto', 'verbose_name_plural': 'Votos'},
        ),
        migrations.AlterField(
            model_name='isue',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='isue',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='minute',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='minute',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='minute',
            name='location',
            field=models.CharField(max_length=250, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='minute',
            name='table',
            field=models.TextField(verbose_name='Tabla'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='isue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Isue'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
