# Generated by Django 3.0.5 on 2020-04-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200413_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minute_assistants',
            options={'verbose_name': 'Asistentes a Acta', 'verbose_name_plural': 'Asistentes a Actas'},
        ),
    ]
