# Generated by Django 3.0.5 on 2020-04-19 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200416_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='player',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='record',
        ),
        migrations.RemoveField(
            model_name='played',
            name='match',
        ),
        migrations.RemoveField(
            model_name='played',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position_one',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position_two',
        ),
        migrations.RemoveField(
            model_name='player',
            name='records',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.RemoveField(
            model_name='training',
            name='players',
        ),
        migrations.DeleteModel(
            name='Assistants',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
        migrations.DeleteModel(
            name='Played',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
