# Generated by Django 3.0.5 on 2020-05-23 19:42

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200419_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='minute',
            name='locationGPS',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [-71.24076894770667, -29.915835830267262], 'marker_color': 'blue'}, null=True),
        ),
    ]
