# Generated by Django 3.0.5 on 2020-06-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_minute_locationgps'),
    ]

    operations = [
        migrations.AddField(
            model_name='isue',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='isue',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='isue',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
