# Generated by Django 3.0.5 on 2020-06-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200610_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isue',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
